// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBls-Ns0xZH3Djb_pdFpNt2KJd9ibSsB2w',
    appId: '1:415768267954:web:0477b7635002fb07938dab',
    messagingSenderId: '415768267954',
    projectId: 'cis3334-firestore-allielopez',
    authDomain: 'cis3334-firestore-allielopez.firebaseapp.com',
    storageBucket: 'cis3334-firestore-allielopez.firebasestorage.app',
    measurementId: 'G-5MG2S8Y6KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA90dAl97wX-JraFZkuW89KO5i7ei96Tbk',
    appId: '1:415768267954:android:b9cbe8a044427694938dab',
    messagingSenderId: '415768267954',
    projectId: 'cis3334-firestore-allielopez',
    storageBucket: 'cis3334-firestore-allielopez.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBls-Ns0xZH3Djb_pdFpNt2KJd9ibSsB2w',
    appId: '1:415768267954:web:4b69de207b961986938dab',
    messagingSenderId: '415768267954',
    projectId: 'cis3334-firestore-allielopez',
    authDomain: 'cis3334-firestore-allielopez.firebaseapp.com',
    storageBucket: 'cis3334-firestore-allielopez.firebasestorage.app',
    measurementId: 'G-P3L6HNMKR6',
  );
}
